_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "https://drive.google.com/file/d/1vG9XEXkIavakNI_mTWdTFmOTUAUUz3Ih/view?usp=sharing"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
